apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: datastreaming
  labels:
    name: kafka-service
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
    #targetPort: 9094
    #nodePort: 32654
  selector:
    app: kafka-broker
