apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  namespace: datastreaming
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-container
        image: bitnami/zookeeper:3.7.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name : ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_AUTOPURGE_INTERVAL
          value: "1"
        - name: ZOO_AUTOPURGE_RETAIN_COUNT
          value: "3"
        volumeMounts:
        - mountPath: /bitnami/zookeeper
          name: zookeeper-data
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: datastream-pvc
