apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: datastreaming
  labels:
    app: schema-registry-svc
spec:
  clusterIP: None
  ports:
    - name: schema-registry
      protocol: TCP
      port: 8081
  selector:
    app: schema-registry
